import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.JAEHA_BUDGET_CONFIG||{},root=document.querySelector('#app');
if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){root.innerHTML='Supabase config 오류';throw Error('config')}
const db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
let user=null,tx=[],settings={custom_categories:[],savings_goals:[]},month=new Date(),view='홈',filter='전체',statKind='지출';
const kinds=['수입','지출','저축','투자'],defaults={수입:['급여','부업','용돈','캐시백','이자','기타'],지출:['식비','데이트비','구독서비스','통신요금','쇼핑','교통비','의료비','여가생활비','기타'],저축:['적금','예금','청약','비상금','기타'],투자:['매수','매도','배당','배당금']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>new Intl.NumberFormat('ko-KR').format(Math.round(Number(n||0))),won=n=>'₩'+num(n),ym=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const date=iso=>{let d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const inv=t=>t.kind==='투자'?(String(t.category).includes('매수')?'buy':(String(t.category).includes('매도')||String(t.category).includes('배당')?'plus':'other')):null;
const sign=t=>t.kind==='수입'||inv(t)==='plus'?'+':t.kind==='지출'||inv(t)==='buy'?'−':'';
const money=t=>sign(t)+won(t.amount);
function calc(v){let s=String(v).replace(/,/g,'').trim();if(!/^[0-9+\-*/().\s]+$/.test(s))throw Error('금액을 확인해주세요.');let n=Function(`"use strict";return (${s})`)();if(!Number.isFinite(n)||n<0)throw Error('금액을 확인해주세요.');return Math.round(n)}
function sum(a){let k=x=>a.filter(t=>t.kind===x).reduce((s,t)=>s+Number(t.amount),0),plus=a.filter(t=>inv(t)==='plus').reduce((s,t)=>s+Number(t.amount),0),buy=a.filter(t=>inv(t)==='buy').reduce((s,t)=>s+Number(t.amount),0),income=k('수입'),expense=k('지출'),saving=k('저축');return{income,expense,saving,plus,buy,balance:income+plus-expense-buy}}
const monthly=()=>tx.filter(t=>date(t.date).startsWith(ym(month)));
async function load(){let[{data:a,error:e},{data:b,error:f}]=await Promise.all([db.from('transactions').select('*').order('date',{ascending:false}),db.from('settings').select('*').eq('user_id',user.id).maybeSingle()]);if(e||f)throw(e||f);tx=a||[];settings=b||settings;render()}
function auth(msg=''){root.innerHTML=`<main class="auth"><h1>재하 가계부</h1><form id="login" class="panel"><label>이메일</label><input name="email" type="email" required><label>비밀번호</label><input name="password" type="password" required><div class="actions"><button>로그인</button><button type="button" class="soft" id="signup">첫 계정 만들기</button></div><p>${esc(msg)}</p></form></main>`;let f=root.querySelector('#login');f.onsubmit=async e=>{e.preventDefault();let x=new FormData(f),{error}=await db.auth.signInWithPassword({email:x.get('email'),password:x.get('password')});if(error)auth(error.message)};root.querySelector('#signup').onclick=async()=>{let x=new FormData(f),{error}=await db.auth.signUp({email:x.get('email'),password:x.get('password')});auth(error?error.message:'이메일 인증 후 로그인하세요.')}}
const nav=()=>`<header class="nav"><div>${['홈','내역','캘린더','통계','설정'].map(x=>`<button data-view="${x}" class="${view===x?'on':''}">${x}</button>`).join('')}</div><button id="add" class="add">＋</button></header>`;
const monthbar=()=>`<div class="month"><button id="prev">‹</button><div><b>${month.getFullYear()}년 ${month.getMonth()+1}월</b><button id="today">오늘</button></div><button id="next">›</button></div>`;
function cards(s){return `<div class="cards"><article><span>↙　수입</span><b>+${won(s.income)}</b></article><article><span>↗　지출</span><b>−${won(s.expense)}</b></article><article><span>▣　저축</span><b>${won(s.saving)}</b></article><article><span>⌁　투자</span><div class="invest"><small>매도·배당<b>+${won(s.plus)}</b></small><small>매수<b>−${won(s.buy)}</b></small></div></article></div>`}
function rows(a){return a.length?`<div class="rows">${a.map(t=>`<div class="row" data-id="${t.id}"><div><b>${esc(t.title)}</b><small>${esc(t.category)} · ${date(t.date).slice(5).replace('-','/')}</small></div><strong>${money(t)}</strong></div>`).join('')}</div>`:`<div class="empty">거래가 없어요.</div>`}
function home(){let a=monthly(),s=sum(a);return `${monthbar()}<section class="balance"><span>이번 달 생활수지</span><b>${s.balance<0?'−':'+'}${won(Math.abs(s.balance))}</b><small>수입 + 매도·배당 − 지출 − 매수</small></section>${cards(s)}<h3>저축 목표 <small>＋ 추가</small></h3><div class="goal">◎　목표를 만들어보세요<br><small>목표 금액과 현재 금액을 기록해 진행률을 볼 수 있어요.</small></div><h3>최근 내역 <small>8건 표시</small></h3>${rows(a.slice(0,8))}`}
function history(){let a=monthly(),b=filter==='전체'?a:a.filter(t=>t.kind===filter);return `<div class="tools"><input id="search" placeholder="⌕ 이름, 카테고리, 메모 검색">${monthbar()}<div class="tabs">${['전체',...kinds].map(x=>`<button data-filter="${x}" class="${filter===x?'on':''}">${x}</button>`).join('')}</div></div><div id="result">${rows(b)}</div>`}
function calendar(){let y=month.getFullYear(),m=month.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),c='';for(let i=0;i<42;i++){let n=i-start+1,d=n<1?new Date(y,m-1,prev+n,12):n>days?new Date(y,m+1,n-days,12):new Date(y,m,n,12),key=date(d.toISOString()),a=tx.filter(t=>date(t.date)===key);c+=`<div class="day ${d.getMonth()!==m?'other':''}"><div>${d.getDate()}<button data-date="${key}">＋</button></div>${a.slice(0,3).map(t=>`<p data-id="${t.id}"><b>${esc(t.title)}</b><br>${money(t)}</p>`).join('')}${a.length>3?`<small>+${a.length-3}건</small>`:''}</div>`}return `${monthbar()}<div class="week">${['월','화','수','목','금','토','일'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar">${c}</div>`}
function stats(){let y=month.getFullYear(),v=[];for(let m=0;m<12;m++){let s=sum(tx.filter(t=>new Date(t.date).getFullYear()===y&&new Date(t.date).getMonth()===m));v.push(statKind==='수입'?s.income:statKind==='지출'?s.expense:statKind==='저축'?s.saving:statKind==='투자'?s.plus-s.buy:s.balance)}let mx=Math.max(1,...v.map(Math.abs));return `<div class="statTabs">${['수입','지출','저축','투자','생활수지'].map(x=>`<button data-stat="${x}" class="${statKind===x?'on':''}">${x}</button>`).join('')}</div><div class="year"><button id="py">‹</button><b>${y}년</b><button id="ny">›</button></div><div class="chart">${v.map((x,i)=>`<div><i style="height:${Math.max(2,Math.abs(x)/mx*220)}px"></i><span>${i+1}월</span></div>`).join('')}</div>`}
function settingsHTML(){return `<div class="settings"><h3>데이터</h3><p>기존 Swift 백업을 가져오거나 현재 데이터를 백업합니다.</p><div class="actions"><label class="button">JSON으로 덮어쓰기<input id="import" type="file" accept=".json" hidden></label><button class="soft" id="export">JSON 백업</button></div><p id="datamsg"></p><hr><button class="soft" id="logout">로그아웃</button></div>`}
function render(){root.innerHTML=`<div class="shell">${nav()}<main>${view==='홈'?home():view==='내역'?history():view==='캘린더'?calendar():view==='통계'?stats():settingsHTML()}</main></div>`;bind()}
function bind(){root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});root.querySelector('#add')?.addEventListener('click',()=>sheet());root.querySelector('#prev')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()});root.querySelector('#next')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()});root.querySelector('#today')?.addEventListener('click',()=>{month=new Date();render()});root.querySelectorAll('[data-id]').forEach(r=>r.onclick=()=>sheet(tx.find(t=>t.id===r.dataset.id)));root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>sheet(null,b.dataset.date));root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});root.querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{statKind=b.dataset.stat;render()});root.querySelector('#py')?.addEventListener('click',()=>{month=new Date(month.getFullYear()-1,month.getMonth(),1);render()});root.querySelector('#ny')?.addEventListener('click',()=>{month=new Date(month.getFullYear()+1,month.getMonth(),1);render()});let q=root.querySelector('#search');if(q)q.oninput=()=>{let s=q.value.toLowerCase(),a=monthly().filter(t=>(filter==='전체'||t.kind===filter)&&`${t.title} ${t.category} ${t.note}`.toLowerCase().includes(s));root.querySelector('#result').innerHTML=rows(a);root.querySelectorAll('[data-id]').forEach(r=>r.onclick=()=>sheet(tx.find(t=>t.id===r.dataset.id)))};if(view==='설정')bindSettings()}
function cats(k){let c=(settings.custom_categories||[]).filter(x=>x.kindRawValue===k).map(x=>x.name);return[...new Set([...(defaults[k]||[]),...c])]}
function sheet(t=null,preset=null){let editing=!!t?.id,k=t?.kind||'지출',el=document.createElement('div');el.className='modal';el.innerHTML=`<form class="sheet"><h2>${editing?'거래 수정':'거래 추가'}</h2><label>날짜</label><input name="date" type="date" value="${preset||(t?date(t.date):date(new Date().toISOString()))}"><label>구분</label><div class="kind">${kinds.map(x=>`<button type="button" data-kind="${x}" class="${x===k?'on':''}">${x}</button>`).join('')}</div><input name="kind" type="hidden" value="${k}"><label>카테고리</label><select name="category"></select><label>금액</label><input name="amount" inputmode="decimal" value="${t?num(t.amount):''}"><small id="preview"></small><label>이름</label><input name="title" value="${esc(t?.title||'')}"><label>메모</label><textarea name="note">${esc(t?.note||'')}</textarea><p id="msg"></p><div class="actions">${editing?'<button type="button" class="soft copy">복사</button><button type="button" class="soft repeat">반복</button><button type="button" class="soft delete">삭제</button>':''}<button type="button" class="soft cancel">취소</button><button>저장</button></div></form>`;document.body.append(el);let f=el.querySelector('form'),ki=f.elements.kind,cs=f.elements.category,ai=f.elements.amount,p=el.querySelector('#preview'),fill=()=>cs.innerHTML=cats(ki.value).map(x=>`<option ${x===t?.category?'selected':''}>${esc(x)}</option>`).join('');fill();el.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{el.querySelectorAll('[data-kind]').forEach(x=>x.classList.remove('on'));b.classList.add('on');ki.value=b.dataset.kind;fill()});ai.oninput=()=>{let r=ai.value.replace(/,/g,'');if(/^[0-9]+$/.test(r)){ai.value=num(r);p.textContent=''}else try{p.textContent=/[+\-*/]/.test(r)?'= '+num(calc(r)):''}catch{p.textContent=''}};ai.onblur=()=>{try{if(/[+\-*/]/.test(ai.value)){ai.value=num(calc(ai.value));p.textContent=''}}catch{}};el.querySelector('.cancel').onclick=()=>el.remove();f.onsubmit=async e=>{e.preventDefault();try{let d=new FormData(f),payload={user_id:user.id,title:String(d.get('title')).trim(),date:new Date(d.get('date')+'T12:00:00').toISOString(),kind:d.get('kind'),category:d.get('category'),amount:calc(d.get('amount')),note:String(d.get('note')).trim()},{error}=editing?await db.from('transactions').update(payload).eq('id',t.id):await db.from('transactions').insert(payload);if(error)throw error;el.remove();await load()}catch(e){el.querySelector('#msg').textContent=e.message}};if(editing){el.querySelector('.delete').onclick=async()=>{if(confirm('삭제할까요?')){let{error}=await db.from('transactions').delete().eq('id',t.id);if(error)alert(error.message);else{el.remove();await load()}}};el.querySelector('.copy').onclick=()=>{let c={...t,id:null,date:new Date().toISOString()};el.remove();sheet(c)};el.querySelector('.repeat').onclick=()=>alert('반복 기능의 세부 설정 화면은 2차 수정에서 기존 앱 방식으로 복원할게요.')}}
function bindSettings(){root.querySelector('#logout').onclick=()=>db.auth.signOut();let imp=root.querySelector('#import');imp.onchange=async()=>{let file=imp.files[0];if(!file||!confirm('현재 데이터를 지우고 이 JSON으로 덮어쓸까요?'))return;let msg=root.querySelector('#datamsg');try{let snap=JSON.parse(await file.text());if(!Array.isArray(snap.transactions))throw Error('지원하지 않는 파일');let r=await db.from('transactions').delete().eq('user_id',user.id);if(r.error)throw r.error;let a=snap.transactions.map(t=>({user_id:user.id,title:t.title,date:t.date,kind:t.kindRawValue||t.kind,category:t.category,amount:t.amount,note:t.note||'',created_at:t.createdAt||new Date().toISOString(),repeat_series_id:t.repeatSeriesID||null,repeat_frequency:t.repeatFrequencyRawValue||null,repeat_interval:t.repeatInterval||1,repeat_sequence:t.repeatSequence||0,repeat_anchor_date:t.repeatAnchorDate||null}));for(let i=0;i<a.length;i+=200){let{error}=await db.from('transactions').insert(a.slice(i,i+200));if(error)throw error}let{error}=await db.from('settings').upsert({user_id:user.id,custom_categories:snap.customCategories||[],monthly_budgets:[],savings_goals:snap.savingsGoals||[],updated_at:new Date().toISOString()});if(error)throw error;msg.textContent=`완료: ${a.length}건`;await load()}catch(e){msg.textContent='실패: '+e.message}};root.querySelector('#export').onclick=()=>{let snap={formatVersion:1,exportedAt:new Date().toISOString(),transactions:tx.map(t=>({title:t.title,date:t.date,kindRawValue:t.kind,category:t.category,amount:Number(t.amount),note:t.note,createdAt:t.created_at,repeatSeriesID:t.repeat_series_id,repeatFrequencyRawValue:t.repeat_frequency,repeatInterval:t.repeat_interval,repeatSequence:t.repeat_sequence,repeatAnchorDate:t.repeat_anchor_date})),customCategories:settings.custom_categories||[],savingsGoals:settings.savings_goals||[]},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(snap,null,2)],{type:'application/json'}));a.download=`JaehaBudget_${new Date().toISOString().slice(0,10)}.json`;a.click()}}
db.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user)try{await load()}catch(e){root.innerHTML='DB 오류: '+esc(e.message)}else auth()});let{data:{session}}=await db.auth.getSession();user=session?.user||null;if(user)await load();else auth();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
