import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.JAEHA_BUDGET_CONFIG||{};
const root=document.querySelector('#app');
if(!cfg.supabaseUrl||!cfg.supabasePublishableKey||cfg.supabaseUrl.includes('YOUR_PROJECT')){root.innerHTML=`<main class="auth"><h1>재하 가계부</h1><div class="card"><b>Supabase 연결이 필요해요.</b><p class="sub">config.example.js를 config.js로 복사한 뒤 프로젝트 URL과 Publishable key를 입력하세요.</p></div></main>`;throw new Error('Missing config')}
const db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
let user=null, tx=[], settings={custom_categories:[],monthly_budgets:[],savings_goals:[]}, month=new Date();
const kinds=['수입','지출','저축','투자'];
const defaults={'수입':['급여','부업','용돈','캐시백','이자','기타'],'지출':['식비','데이트비','구독서비스','통신요금','쇼핑','교통비','의료비','여가생활비','기타'],'저축':['적금','예금','청약','비상금','기타'],'투자':['매수','매도','배당금']};
const won=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0))+'원';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ym=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const localDate=iso=>{const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function calcExpr(v){const s=v.replace(/,/g,'').trim();if(!s)return 0;if(!/^[0-9+\-*/().\s]+$/.test(s))throw Error('숫자와 + - * / 만 사용할 수 있어요.');const n=Function(`"use strict";return (${s})`)();if(!Number.isFinite(n)||n<0)throw Error('금액을 확인해주세요.');return Math.round(n)}
async function load(){const [{data:a,error:e1},{data:b,error:e2}]=await Promise.all([db.from('transactions').select('*').order('date',{ascending:false}),db.from('settings').select('*').eq('user_id',user.id).maybeSingle()]);if(e1||e2)throw(e1||e2);tx=a||[];settings=b||settings;render()}
function authView(msg=''){root.innerHTML=`<main class="auth"><h1>재하 가계부</h1><p class="sub">내 기기에서만 로그인해 사용하는 개인 가계부</p><form id="login" class="card"><label>이메일</label><input name="email" type="email" required autocomplete="email"><label>비밀번호</label><input name="password" type="password" required autocomplete="current-password"><div class="actions"><button>로그인</button><button type="button" class="ghost" id="signup">첫 계정 만들기</button></div>${msg?`<p class="sub">${esc(msg)}</p>`:''}</form></main>`;const f=root.querySelector('#login');f.addEventListener('submit',async e=>{e.preventDefault();const x=new FormData(f);const {error}=await db.auth.signInWithPassword({email:x.get('email'),password:x.get('password')});if(error)authView(error.message)});root.querySelector('#signup').addEventListener('click',async()=>{const x=new FormData(f);const {error}=await db.auth.signUp({email:x.get('email'),password:x.get('password')});authView(error?error.message:'계정을 만들었어요. 이메일 확인이 켜져 있다면 메일 인증 후 로그인하세요.')})}
function render(){const key=ym(month), mtx=tx.filter(t=>localDate(t.date).startsWith(key));const sums=Object.fromEntries(kinds.map(k=>[k,mtx.filter(t=>t.kind===k).reduce((s,t)=>s+Number(t.amount),0)]));const plan=(settings.monthly_budgets||[]).find(x=>x.monthKey===key);const budget=plan?.totalLimit||0;const spent=sums['지출'];root.innerHTML=`<div class="shell"><header class="top"><div><h1>재하 가계부</h1><div class="sub">${esc(user.email||'')}</div></div><button class="ghost" id="logout">로그아웃</button></header><div class="monthbar card"><button id="prev">‹</button><b>${month.getFullYear()}년 ${month.getMonth()+1}월</b><button id="next">›</button></div><section class="summary">${kinds.map(k=>`<div class="metric"><span class="${k==='수입'?'income':k==='지출'?'expense':k==='저축'?'saving':'investment'}">${k}</span><b>${won(sums[k])}</b></div>`).join('')}</section>${budget?`<section class="card"><div class="row"><div><b>이번 달 생활비 예산</b><div class="row-meta">${won(spent)} / ${won(budget)}</div></div><b>${Math.round(spent/budget*100)}%</b></div><div class="budgetline"><span style="width:${Math.min(100,spent/budget*100)}%"></span></div></section>`:''}<nav class="tabs card"><button class="tab active" data-filter="전체">전체</button>${kinds.map(k=>`<button class="tab" data-filter="${k}">${k}</button>`).join('')}<button class="tab" data-filter="설정">설정</button></nav><section id="content">${listHTML(mtx)}</section><button class="fab" id="add" aria-label="거래 추가">+</button></div>`;root.querySelector('#logout').onclick=()=>db.auth.signOut();root.querySelector('#prev').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()};root.querySelector('#next').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()};root.querySelector('#add').onclick=()=>transactionSheet();root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{root.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;root.querySelector('#content').innerHTML=f==='설정'?settingsHTML():listHTML(f==='전체'?mtx:mtx.filter(t=>t.kind===f));bindRows();if(f==='설정')bindSettings()});bindRows()}
function listHTML(items){if(!items.length)return `<div class="card empty">이 달의 거래가 없어요.</div>`;return `<div class="card">${items.map(t=>`<div class="row txrow" data-id="${t.id}"><div><div class="row-title">${esc(t.title)}</div><div class="row-meta">${localDate(t.date)} · ${esc(t.category)}${t.note?' · '+esc(t.note):''}</div></div><div class="amount ${t.kind==='수입'?'income':t.kind==='지출'?'expense':t.kind==='저축'?'saving':'investment'}">${won(t.amount)}</div></div>`).join('')}</div>`}
function bindRows(){root.querySelectorAll('.txrow').forEach(r=>r.onclick=()=>transactionSheet(tx.find(t=>t.id===r.dataset.id)))}
function categories(kind){const custom=(settings.custom_categories||[]).filter(x=>x.kindRawValue===kind).map(x=>x.name);return [...new Set([...(defaults[kind]||[]),...custom])]}
function transactionSheet(t=null){const kind=t?.kind||'지출';const el=document.createElement('div');el.className='modal';el.innerHTML=`<form class="sheet"><h2>${t?'거래 수정':'거래 추가'}</h2><div class="grid2"><div><label>종류</label><select name="kind">${kinds.map(k=>`<option ${k===kind?'selected':''}>${k}</option>`).join('')}</select></div><div><label>날짜</label><input name="date" type="date" value="${t?localDate(t.date):localDate(new Date().toISOString())}" required></div></div><label>내용</label><input name="title" value="${esc(t?.title||'')}" required><div class="grid2"><div><label>카테고리</label><select name="category"></select></div><div><label>금액 (400*2처럼 계산 가능)</label><input name="amount" inputmode="decimal" value="${t?.amount||''}" required></div></div><label>메모</label><textarea name="note">${esc(t?.note||'')}</textarea><p class="sub" id="formmsg"></p><div class="actions"><button type="submit">저장</button><button type="button" class="ghost cancel">취소</button>${t?'<button type="button" class="danger delete">삭제</button>':''}</div></form>`;document.body.append(el);const f=el.querySelector('form'), ks=f.elements.kind, cs=f.elements.category;const fill=()=>{const cur=t?.category;cs.innerHTML=categories(ks.value).map(c=>`<option ${c===cur?'selected':''}>${esc(c)}</option>`).join('')};fill();ks.onchange=fill;el.querySelector('.cancel').onclick=()=>el.remove();el.addEventListener('click',e=>{if(e.target===el)el.remove()});f.onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(f),amount=calcExpr(String(fd.get('amount'))),payload={user_id:user.id,title:String(fd.get('title')).trim(),date:new Date(String(fd.get('date'))+'T12:00:00').toISOString(),kind:fd.get('kind'),category:fd.get('category'),amount,note:String(fd.get('note')).trim()};const q=t?db.from('transactions').update(payload).eq('id',t.id):db.from('transactions').insert(payload);const {error}=await q;if(error)throw error;el.remove();await load()}catch(err){el.querySelector('#formmsg').textContent=err.message}};if(t)el.querySelector('.delete').onclick=async()=>{if(confirm('이 거래를 삭제할까요?')){const {error}=await db.from('transactions').delete().eq('id',t.id);if(error)alert(error.message);else{el.remove();await load()}}}}
function settingsHTML(){return `<div class="card"><h3>데이터</h3><p class="sub">기존 Swift 앱의 JaehaBudget_Sync.json을 가져오면 현재 웹 DB 내용을 전부 교체합니다.</p><div class="actions"><label class="button" style="display:inline-flex;align-items:center">JSON으로 덮어쓰기<input id="import" type="file" accept="application/json,.json" hidden></label><button class="ghost" id="export">JSON 백업</button></div><p class="sub" id="datamsg"></p></div><div class="card"><h3>월 예산</h3><label>${ym(month)} 총 지출 예산</label><input id="budget" inputmode="numeric" value="${(settings.monthly_budgets||[]).find(x=>x.monthKey===ym(month))?.totalLimit||''}" placeholder="0"><button id="savebudget" style="margin-top:10px">저장</button></div>`}
function bindSettings(){const imp=root.querySelector('#import');imp.onchange=async()=>{const file=imp.files[0];if(!file)return;if(!confirm('웹 DB의 현재 거래와 설정을 모두 지우고 이 JSON 내용으로 덮어쓸까요?'))return;const msg=root.querySelector('#datamsg');try{msg.textContent='가져오는 중…';const snap=JSON.parse(await file.text());if(!Array.isArray(snap.transactions))throw Error('지원하지 않는 백업 파일이에요.');let r=await db.from('transactions').delete().eq('user_id',user.id);if(r.error)throw r.error;const rows=snap.transactions.map(t=>({user_id:user.id,title:t.title,date:t.date,kind:t.kindRawValue||t.kind,category:t.category,amount:t.amount,note:t.note||'',created_at:t.createdAt||new Date().toISOString(),repeat_series_id:t.repeatSeriesID||null,repeat_frequency:t.repeatFrequencyRawValue||null,repeat_interval:t.repeatInterval||1,repeat_sequence:t.repeatSequence||0,repeat_anchor_date:t.repeatAnchorDate||null}));for(let i=0;i<rows.length;i+=200){const {error}=await db.from('transactions').insert(rows.slice(i,i+200));if(error)throw error}const s={user_id:user.id,custom_categories:snap.customCategories||[],monthly_budgets:snap.monthlyBudgets||[],savings_goals:snap.savingsGoals||[],updated_at:new Date().toISOString()};const {error}=await db.from('settings').upsert(s);if(error)throw error;msg.textContent=`완료: 거래 ${rows.length}건을 가져왔어요.`;await load()}catch(e){msg.textContent='가져오기 실패: '+e.message}};root.querySelector('#export').onclick=()=>{const snap={formatVersion:1,exportedAt:new Date().toISOString(),transactions:tx.map(t=>({title:t.title,date:t.date,kindRawValue:t.kind,category:t.category,amount:Number(t.amount),note:t.note,createdAt:t.created_at,repeatSeriesID:t.repeat_series_id,repeatFrequencyRawValue:t.repeat_frequency,repeatInterval:t.repeat_interval,repeatSequence:t.repeat_sequence,repeatAnchorDate:t.repeat_anchor_date})),customCategories:settings.custom_categories||[],monthlyBudgets:settings.monthly_budgets||[],savingsGoals:settings.savings_goals||[]};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(snap,null,2)],{type:'application/json'}));a.download=`JaehaBudget_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};root.querySelector('#savebudget').onclick=async()=>{try{const val=calcExpr(root.querySelector('#budget').value||'0'),key=ym(month),arr=[...(settings.monthly_budgets||[])].filter(x=>x.monthKey!==key);if(val>0)arr.push({monthKey:key,totalLimit:val,categoryLimits:{}});const {error}=await db.from('settings').upsert({user_id:user.id,custom_categories:settings.custom_categories||[],monthly_budgets:arr,savings_goals:settings.savings_goals||[],updated_at:new Date().toISOString()});if(error)throw error;await load()}catch(e){alert(e.message)}}}
db.auth.onAuthStateChange(async(_,session)=>{user=session?.user||null;if(user){try{await load()}catch(e){root.innerHTML=`<main class="auth"><div class="card">DB 오류: ${esc(e.message)}<br><span class="sub">schema.sql을 Supabase SQL Editor에서 실행했는지 확인하세요.</span></div></main>`}}else authView()});
const {data:{session}}=await db.auth.getSession();user=session?.user||null;if(user)await load();else authView();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
